plugins {
    id 'java'
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}

bootJar {
    enabled = false
}

jar {
    enabled = true
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

dependencies {
    implementation project(':common')
    implementation 'org.projectlombok:lombok:1.18.22'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    //    implementation 'org.springframework.boot:spring-boot-starter-oauth2-authorization-server'
//    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
//    implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    testImplementation 'org.springframework.security:spring-security-test'
    api 'io.jsonwebtoken:jjwt-api:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5' // jackson 기반
    implementation 'org.springframework.boot:spring-boot-starter'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    compileOnly 'javax.servlet:javax.servlet-api:4.0.1'

    implementation 'io.projectreactor:reactor-core:3.6.10'
}

//def activeProfile = project.hasProperty('profile') ? project.property('profile') : 'local'
//processResources {
//    // 기존 모듈의 리소스 디렉토리 유지
//    from(sourceSets.main.resources.srcDirs)
//
//    // 루트 프로젝트의 공통 리소스 디렉토리 (배너 파일 등) 복사
//    from(rootProject.file("src/main/resources")) {
//        include "banner.txt"
//        into "."
//    }
//
//    // 활성화된 프로파일에 해당하는 설정 파일만 복사
//    // 1. 모듈별 공통
//    from(rootProject.file("src/main/resources/config/${project.name}/application.yml")) {
//        into "."
//    }
//     2. 모듈별 profile별 설정
//    from(rootProject.file("src/main/resources/config/${project.name}/${activeProfile}")) {
//        // 복사할 대상 폴더
//        into "build/resources/main"
//
//        // 파일 이름 변경
//        rename { String fileName ->
//            if (fileName.endsWith(".yml")) {
//                return "application-core-${activeProfile}.yml"
//            }
//            return fileName
//        }
//    }
//}