spring:
  threads:
    virtual:
      enabled: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration
  profiles:
    active: local
  application:
     name: bwg-channel-backend-auth-svc
  devtools:
    livereload:
      #enabled: true
      #자동 재시작 시 내부 서브컨텍스트(NamedContextFactory)까지 강제로 내려버리기 때문에
      #gateway + loadbalancer 조합에서 문제가 생김
      #개발시 수동 재시작 권장하고 필요할때만 true 변경할것
      enabled: false
    restart:
      log-condition-evaluation-delta: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  web:
    resources:
      add-mappings: false
  main:
    allow-bean-definition-overriding: true

server:
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-response: true
    context-path: /auth
# actuator
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: never  # health 상태 상세 보기
  info:
    git:
      mode: simple
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
info:
  app:
    name: channel-backend-auth
    version: 0.0.1
    company: BankwareGlobal

logging:
  file:
    name: ${app.log-path}/${spring.application.name}.log
  logback:
    rollingpolicy:
      file-name-pattern: ${app.log-path}/${spring.application.name}-%d{yyyy-MM-dd}.%i.log.gz
      max-file-size: 100MB
      max-history: 30
      total-size-cap: 3GB