spring:
  threads:
    virtual:
      enabled: true
  profiles:
    active: local
  application:
     name: bwg-channel-backend-discovery
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
