spring:
  config:
    import: "classpath:/application-securitycommon-local.yml"   # security-common 설정 import
  lifecycle:
    timeout-per-shutdown-phase: 35s
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true    # local 개발 편의: 서비스 직접 라우팅 허용 (dev/운영은 공통 설정에서 off)
server:
  port: 18081
  shutdown: graceful
eureka:
  instance:
    prefer-ip-address: false
    hostname: localhost
    ip-address: localhost
  client:
    service-url:
      defaultZone: "http://localhost:18761/eureka"
    register-with-eureka: true    # Gateway를 Eureka에 등록
    fetch-registry: true          # 다른 서비스 정보 조회 가능
app:
  test: "api-gateway"
  log-path: ./logs
  cors:
    allowed-origin-patterns:
      - http://localhost:8000
      - http://127.0.0.1:8000

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
  thymeleaf:
    cache: false
