[versions]
# Spring Cloud BOM (Boot BOM은 org.springframework.boot 플러그인이 자동 적용)
springCloud = "2023.0.1"

# Boot BOM이 관리하지 않는 서드파티 라이브러리 버전
springdoc = "2.6.0"
mybatisSpringBoot = "3.0.4"
jjwt = "0.11.5"
p6spy = "1.9.1"

[libraries]
springdoc-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }
springdoc-webflux-ui = { module = "org.springdoc:springdoc-openapi-starter-webflux-ui", version.ref = "springdoc" }
springdoc-common = { module = "org.springdoc:springdoc-openapi-starter-common", version.ref = "springdoc" }

mybatis-spring-boot-starter = { module = "org.mybatis.spring.boot:mybatis-spring-boot-starter", version.ref = "mybatisSpringBoot" }

jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }

p6spy-spring-boot-starter = { module = "com.github.gavlyukovskiy:p6spy-spring-boot-starter", version.ref = "p6spy" }
