spring:
  config:
    import: "classpath:/application-securitycommon-dev.yml"   # security-common 설정 import
  lifecycle:
    timeout-per-shutdown-phase: 35s
server:
  port: 18081
  shutdown: graceful
eureka:
  instance:
    prefer-ip-address: false
    hostname: localhost
    ip-address: localhost
  client:
    service-url:
      defaultZone: "http://192.168.110.217:18761/eureka"
    register-with-eureka: true
    fetch-registry: true
app:
  test: "api-gateway"
  log-path: /Users/channelunit/apps/bx-cf-be/logs
  cors:
    allowed-origin-patterns:
      - http://192.168.110.217
      - http://localhost:3000
      - http://127.0.0.1:3000
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: INFO
