spring:
  datasource:
    # 'jpa-main' DataSource (JPA용)
    jpa-main:
      jdbc-url: jdbc:postgresql://192.168.110.217:5432/bxcfdb
      driver-class-name: org.postgresql.Driver
      username: bxcf
      password: "1111"
      hikari:
        pool-name: jpa-main-hikari-pool
    # 'mybatis-main' DataSource (MyBatis용)
    mybatis-main:
      jdbc-url: jdbc:postgresql://192.168.110.217:5432/bxcfdb
      driver-class-name: org.postgresql.Driver
      username: bxcf
      password: "1111"
      hikari:
        pool-name: mybatis-main-hikari-pool

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: true

  config:
    import: "classpath:/application-securitycommon-local.yml"
  lifecycle:
    timeout-per-shutdown-phase: 35s

  # valkey
  data:
    redis:
      host: 192.168.110.217
      port: 6379
      timeout: 2s

server:
  tomcat:
    max-swallow-size: -1
  port: 18082
  shutdown: graceful

eureka:
  instance:
    prefer-ip-address: false
    hostname: localhost
    ip-address: localhost
  client:
    service-url:
      defaultZone: "http://localhost:18761/eureka"
    register-with-eureka: true
    fetch-registry: true

app:
  erp-login-url: "https://erp.bankwareglobal.com/serviceEndpoint/httpService/request.json"
  log-path: C:/work/bx-cf-be/logs
  auth:
    refresh-cookie:
      name: refreshToken
      path: /channel/backend/api/v1/auth
      same-site: Lax
      secure: false
      max-age-seconds: 604800

logging:
  level:
    p6spy: INFO

p6spy:
  engine:
    spy:
      log-message-format: com.p6spy.engine.spy.appender.MultiLineFormat
